# Generated by Django 5.2.5 on 2025-09-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rename_transactions_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food'), ('RENT', 'Rent'), ('TRANSPORTATION', 'Transportation'), ('ENTERTAINMENT', 'Entertainment'), ('UTILITIES', 'Utilities'), ('HEALTH', 'Health'), ('OTHER', 'Other'), ('PAYCHECK', 'Paycheck'), ('RSUS', 'RSUs'), ('BONUS', 'Bonus'), ('CAPITAL_GAIN', 'Capital Gain'), ('DIVIDEND', 'Dividend')], max_length=20),
        ),
    ]
